---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-doom
  labels:
    app: app-kubedoom
  namespace: kubedoom
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: app-kubedoom
  template:
    metadata:
      labels:
        app: app-kubedoom
    spec:
      hostNetwork: true
      serviceAccountName: kubedoom
      containers:
      - image: storaxdev/kubedoom:0.5.0
        name: kubedoom
        ports:
        - containerPort: 5900
          protocol: TCP
        
