---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-doom
  labels:
    app: kubedoom
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: my-app-doom
  template:
    metadata:
      namespace: kubedoom
      labels:
        app: my-app-doom
    spec:
      hostNetwork: true
      serviceAccountName: kubedoom
      containers:
      - image: storaxdev/kubedoom:0.5.0
        name: kubedoom
        ports:
        - containerPort: 5900
          protocol: TCP
        
